title: JuYoungSaraChoi's Brave new world
email: juyoungsarachoi@naver.com
description: |
  Irreplaceable person
baseurl: ''
url: 'http://JuYoungSaraChoi.github.io'
timezone: Asia/Seoul 

repository: JuYoungSaraChoi/JuYoungSaraChoi.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: opensource@kakaocorp.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
# google_analytics:
#  ua:
#facebook:
#  app_id: '1204347326263800'
#  username: nkakao
#twitter:
#  username: kakaodev
#google_plus:
#  username: kakaodev
github_url:
  username: JuYoungSaraChoi
